# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "d678794c-2056-4801-893f-adf12bd3c66a"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  cert
  sigh
  increment_build_number
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
  gym(
    scheme: "KanjiRyokucha",
    export_method: "app-store",
    include_bitcode: true
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end
